### ISSUE TITLE
Feature: Test IDs

### ISSUE THREAD

**Issue by iamclaytonray** [lifechurch/melos#16]
Would you accept a PR that takes in `testID` props to forward to `data-test-id` on the parent node? (important for e2e testing)

**Comment by tcg** [comment]
Hi, @iamclaytonray! 

If there was a spot where that felt necessary, then *yes, probably*. 

However, we're trying much harder these days to make end-to-end type tests (with Cypress! yay!) "more resilient": https://kentcdodds.com/blog/making-your-ui-tests-resilient-to-change

Specifically, the ideal is the be able to find an element by it's label, placeholder, etc, before resorting to Test ID's (per the recommended order @ https://testing-library.com/docs/guide-which-query )

If a PR adds a test, and that test just doesn't seem do-able without a Test ID, then by all means *yes*.

**Comment by josuablejeru** [comment]
Hi, @tcg is there a possibility to get involved in the Cypress test suite? I used it at work and maybe I can contribute something 😄
